services:
  kingmaker-web:
    build:
      context: .
      args:
        CACHEBUST: ${CACHEBUST:-1}
      no_cache: true
    container_name: kingmaker-web-dev
    image: kazooks/kingmaker:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    restart: unless-stopped