name: CI
on:
  pull_request:
    branches: [master, develop]
  push:
    branches: [master, develop]

jobs:
  test:
    runs-on: node:24-alpine
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Run linting
        run: npm run lint
